name: hivemq-ce
base: core18
version: '2020.6'
summary: HiveMQ CE is a Java-based open source MQTT broker
description:
  HiveMQ CE is a Java-based open source MQTT broker that fully supports MQTT 3.x and MQTT 5.
  HiveMQ CE is the foundation of the HiveMQ enterprise-connectivity and messaging platform and implements all MQTT features.
  This project is the technical core of many large MQTT deployments and is now available as open source software under the Apache 2 license.

grade: devel
confinement: devmode # use 'strict' once you have the right plugs and slots

parts: #parts are used to describe your application,where its various components can be found, its build and run-time requirements, and those of its dependencies.
  hivemq-ce:
    plugin: gradle
    source: https://github.com/hivemq/hivemq-community-edition.git
    source-tag: ‘2020.6’
    gradle-version: ‘6.8.1’
    override-build: |
      - ./gradlew packaging
      - unzip -o /root/parts/hivemq-ce/build/build/zip/hivemq-ce-2020.6.zip -d $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - unzip
    stage-packages:
      - openjdk-11-jre
